<?php

use Illuminate\Database\Seeder;

class AdmissionEmergencyContactsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admission_emergency_contacts')->delete();
        
        \DB::table('admission_emergency_contacts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'admission_student_id' => 1,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-20 13:14:38',
                'updated_at' => '2019-05-29 09:39:47',
            ),
            1 => 
            array (
                'id' => 2,
                'admission_student_id' => 2,
                'full_name' => 'Mrs. Hena Begum',
                'relation' => 'Mother',
                'phone' => '01711120033',
                'email' => NULL,
                'address' => 'Chunarughat, Habiganj.',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 10:43:01',
                'updated_at' => '2019-05-28 11:20:49',
            ),
            2 => 
            array (
                'id' => 3,
                'admission_student_id' => 3,
                'full_name' => 'Md. Taj Uddin',
                'relation' => NULL,
                'phone' => '01711445056',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 10:57:19',
                'updated_at' => '2019-05-28 11:36:23',
            ),
            3 => 
            array (
                'id' => 4,
                'admission_student_id' => 4,
                'full_name' => 'Mst. Amina Begum',
                'relation' => 'Mother',
                'phone' => '01748464302',
                'email' => NULL,
                'address' => 'Nalbohor.
Beanibazar, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 11:13:30',
                'updated_at' => '2019-05-28 12:21:59',
            ),
            4 => 
            array (
                'id' => 5,
                'admission_student_id' => 5,
                'full_name' => 'Dr. Sawjia Islam Amin',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'NEMC Girls Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 11:25:14',
                'updated_at' => '2019-05-28 12:27:40',
            ),
            5 => 
            array (
                'id' => 6,
                'admission_student_id' => 6,
                'full_name' => 'Md. Abdul Wahid',
                'relation' => NULL,
                'phone' => '01711059790',
                'email' => NULL,
                'address' => 'NEMC Secretary',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 12:10:37',
                'updated_at' => '2019-05-28 12:29:04',
            ),
            6 => 
            array (
                'id' => 7,
                'admission_student_id' => 7,
                'full_name' => 'Mst. Sheuli Begum',
                'relation' => 'Mother',
                'phone' => '01745705683',
                'email' => NULL,
                'address' => 'Jalalabad, Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 12:44:02',
                'updated_at' => '2019-05-28 12:30:03',
            ),
            7 => 
            array (
                'id' => 8,
                'admission_student_id' => 8,
                'full_name' => 'Syeda Luna Akther',
                'relation' => 'Mother',
                'phone' => '01741089684',
                'email' => NULL,
                'address' => 'Chunarughat, Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 13:02:49',
                'updated_at' => '2019-05-28 12:33:46',
            ),
            8 => 
            array (
                'id' => 9,
                'admission_student_id' => 9,
                'full_name' => 'Abdul Mutlib',
                'relation' => 'Father',
                'phone' => '01715525165',
                'email' => NULL,
                'address' => 'House No. 1 
Block- A 
Gutatikor R/A 
PO: Kodomtali, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 13:20:25',
                'updated_at' => '2019-05-28 12:34:41',
            ),
            9 => 
            array (
                'id' => 10,
                'admission_student_id' => 10,
                'full_name' => 'Pritush Mohon Datta',
                'relation' => 'Father',
                'phone' => '01749863012',
                'email' => NULL,
                'address' => 'Pritom Medicine House
Srimongal Road, Moulovi Bazar',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 14:01:42',
                'updated_at' => '2019-05-28 12:35:53',
            ),
            10 => 
            array (
                'id' => 11,
                'admission_student_id' => 11,
                'full_name' => 'Dr. Bashir Uddin, Assistant Professor NEMC',
                'relation' => NULL,
                'phone' => '01794153543',
                'email' => NULL,
                'address' => 'NEMC',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-25 14:11:28',
                'updated_at' => '2019-05-28 12:36:52',
            ),
            11 => 
            array (
                'id' => 12,
                'admission_student_id' => 12,
                'full_name' => 'Mohibul goni Panna',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'Shapla Kuthir
House No. 90 
Kazitula Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-27 10:44:01',
                'updated_at' => '2019-05-29 09:41:37',
            ),
            12 => 
            array (
                'id' => 13,
                'admission_student_id' => 13,
                'full_name' => 'Umadur Rahman',
                'relation' => NULL,
                'phone' => '01712030654',
                'email' => NULL,
                'address' => 'Jalalabad Cantonment, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-27 11:14:33',
                'updated_at' => '2019-05-29 09:37:35',
            ),
            13 => 
            array (
                'id' => 14,
                'admission_student_id' => 14,
                'full_name' => 'Muss. Hawarun Nessa Khanom',
                'relation' => 'Mother',
                'phone' => '017100716167',
                'email' => NULL,
                'address' => 'Focus- 105 
Uttar Baluchar, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-27 11:45:24',
                'updated_at' => '2019-05-29 09:38:29',
            ),
            14 => 
            array (
                'id' => 15,
                'admission_student_id' => 15,
                'full_name' => 'Sheikh Monu Miah',
                'relation' => 'Father',
                'phone' => '01737303738',
                'email' => NULL,
                'address' => 'Konirchok, Porgona Bazar
Shahporan, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-27 12:25:32',
                'updated_at' => '2019-05-29 09:38:57',
            ),
            15 => 
            array (
                'id' => 16,
                'admission_student_id' => 16,
                'full_name' => 'Amullya Kumar Ghosh',
                'relation' => 'father',
                'phone' => '01714458257',
                'email' => NULL,
                'address' => 'Kubjhar
PO: Ghorgoan
PS: Rajnagar
Dits: Moulovibazar',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-27 12:59:00',
                'updated_at' => '2019-05-29 09:42:10',
            ),
            16 => 
            array (
                'id' => 17,
                'admission_student_id' => 17,
                'full_name' => 'Shohan Tusher',
                'relation' => NULL,
                'phone' => '01731984535',
                'email' => NULL,
                'address' => 'Fenchuganj
Rajonpur, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-27 13:15:43',
                'updated_at' => '2019-05-29 09:42:44',
            ),
            17 => 
            array (
                'id' => 18,
                'admission_student_id' => 18,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 09:54:28',
                'updated_at' => '2019-05-29 09:43:21',
            ),
            18 => 
            array (
                'id' => 19,
                'admission_student_id' => 19,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 10:14:21',
                'updated_at' => '2019-05-29 09:44:22',
            ),
            19 => 
            array (
                'id' => 20,
                'admission_student_id' => 20,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 10:40:29',
                'updated_at' => '2019-05-29 09:45:05',
            ),
            20 => 
            array (
                'id' => 21,
                'admission_student_id' => 21,
                'full_name' => 'Imran Mahmud Shahjahan',
                'relation' => 'Brother',
                'phone' => '01747685882',
                'email' => NULL,
                'address' => 'Rangdhanu 1/A
Lakhripara
Shibganj, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:07:43',
                'updated_at' => '2019-05-28 12:49:20',
            ),
            21 => 
            array (
                'id' => 22,
                'admission_student_id' => 22,
                'full_name' => 'Amith Deb Joy',
                'relation' => NULL,
                'phone' => '01759032187',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 13:35:08',
                'updated_at' => '2019-05-28 13:35:36',
            ),
            22 => 
            array (
                'id' => 23,
                'admission_student_id' => 23,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:32:46',
                'updated_at' => '2019-05-29 09:34:59',
            ),
            23 => 
            array (
                'id' => 24,
                'admission_student_id' => 24,
                'full_name' => 'Jayed Jomin',
                'relation' => NULL,
                'phone' => '01728138737',
                'email' => NULL,
                'address' => 'Horipur 
Jointa, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 10:52:25',
                'updated_at' => '2019-05-29 10:53:41',
            ),
            24 => 
            array (
                'id' => 25,
                'admission_student_id' => 25,
                'full_name' => 'Nasir Uddin',
                'relation' => NULL,
                'phone' => '01759739850',
                'email' => NULL,
                'address' => 'Mahmudabad R/A
Hobiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 11:35:57',
                'updated_at' => '2019-05-29 11:36:20',
            ),
            25 => 
            array (
                'id' => 26,
                'admission_student_id' => 26,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 11:58:24',
                'updated_at' => '2019-05-29 12:00:08',
            ),
            26 => 
            array (
                'id' => 27,
                'admission_student_id' => 27,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 12:47:47',
                'updated_at' => '2019-05-29 12:48:26',
            ),
            27 => 
            array (
                'id' => 28,
                'admission_student_id' => 28,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 13:17:33',
                'updated_at' => '2019-05-29 13:18:33',
            ),
            28 => 
            array (
                'id' => 29,
                'admission_student_id' => 29,
                'full_name' => 'Abul Khayer',
                'relation' => NULL,
                'phone' => '01719893661',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 14:02:23',
                'updated_at' => '2019-05-29 14:03:34',
            ),
            29 => 
            array (
                'id' => 30,
                'admission_student_id' => 30,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 09:54:06',
                'updated_at' => '2019-05-30 10:07:44',
            ),
            30 => 
            array (
                'id' => 31,
                'admission_student_id' => 31,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 10:28:07',
                'updated_at' => '2019-05-30 10:28:31',
            ),
            31 => 
            array (
                'id' => 32,
                'admission_student_id' => 32,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 10:59:54',
                'updated_at' => '2019-05-30 11:01:00',
            ),
            32 => 
            array (
                'id' => 33,
                'admission_student_id' => 33,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 11:46:07',
                'updated_at' => '2019-05-30 11:46:57',
            ),
            33 => 
            array (
                'id' => 34,
                'admission_student_id' => 34,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 12:50:47',
                'updated_at' => '2019-05-30 12:55:37',
            ),
            34 => 
            array (
                'id' => 35,
                'admission_student_id' => 35,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 13:18:45',
                'updated_at' => '2019-05-30 13:19:16',
            ),
            35 => 
            array (
                'id' => 36,
                'admission_student_id' => 36,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 11:03:31',
                'updated_at' => '2019-06-01 11:03:52',
            ),
            36 => 
            array (
                'id' => 37,
                'admission_student_id' => 37,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 11:54:20',
                'updated_at' => '2019-06-01 11:55:18',
            ),
            37 => 
            array (
                'id' => 38,
                'admission_student_id' => 38,
                'full_name' => 'Dr. Nasim Ahmed',
                'relation' => NULL,
                'phone' => '01711858474',
                'email' => NULL,
                'address' => 'Noor jahan Hospital, Dorgah Gate. Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 12:21:52',
                'updated_at' => '2019-06-01 12:23:52',
            ),
            38 => 
            array (
                'id' => 39,
                'admission_student_id' => 39,
                'full_name' => 'Md. Abdul Jalil',
                'relation' => NULL,
                'phone' => '01738110741',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 12:54:54',
                'updated_at' => '2019-06-01 12:56:27',
            ),
            39 => 
            array (
                'id' => 40,
                'admission_student_id' => 40,
                'full_name' => 'Samar Halda',
                'relation' => NULL,
                'phone' => '01721202895',
                'email' => NULL,
                'address' => 'Pagla Bazar, Sunamganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 13:29:43',
                'updated_at' => '2019-06-01 13:30:13',
            ),
            40 => 
            array (
                'id' => 41,
                'admission_student_id' => 41,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-03 09:53:39',
                'updated_at' => '2019-06-03 09:54:05',
            ),
            41 => 
            array (
                'id' => 42,
                'admission_student_id' => 42,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-03 11:24:57',
                'updated_at' => '2019-06-18 10:05:11',
            ),
            42 => 
            array (
                'id' => 43,
                'admission_student_id' => 43,
                'full_name' => 'Dipika Rani Ray',
                'relation' => 'Mother',
                'phone' => '01748944554',
                'email' => NULL,
                'address' => 'Notunpara
PO: Sachna Baza (3020)
Upozila: Jamalganj
Dist: Sunamganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-03 12:53:37',
                'updated_at' => '2019-06-18 10:06:54',
            ),
            43 => 
            array (
                'id' => 44,
                'admission_student_id' => 44,
                'full_name' => 'Md. Faruk Miah',
                'relation' => NULL,
                'phone' => '01712920426',
                'email' => NULL,
                'address' => 'Rikabi Bazar Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-03 13:23:09',
                'updated_at' => '2019-06-18 10:09:03',
            ),
            44 => 
            array (
                'id' => 45,
                'admission_student_id' => 45,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-09 10:12:51',
                'updated_at' => '2019-06-18 10:10:25',
            ),
            45 => 
            array (
                'id' => 46,
                'admission_student_id' => 46,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-09 10:41:31',
                'updated_at' => '2019-06-18 10:12:00',
            ),
            46 => 
            array (
                'id' => 47,
                'admission_student_id' => 47,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-09 12:04:54',
                'updated_at' => '2019-06-18 10:13:21',
            ),
            47 => 
            array (
                'id' => 48,
                'admission_student_id' => 48,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 11:29:31',
                'updated_at' => '2019-06-18 11:29:54',
            ),
            48 => 
            array (
                'id' => 49,
                'admission_student_id' => 49,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 12:36:43',
                'updated_at' => '2019-06-18 12:36:59',
            ),
            49 => 
            array (
                'id' => 50,
                'admission_student_id' => 50,
                'full_name' => 'Setara Sultana Sweety',
                'relation' => 'Mother',
                'phone' => '01712254481',
                'email' => NULL,
                'address' => 'Vill: Burhanpur
Upozila: Nabiganj
Zila: Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 14:21:10',
                'updated_at' => '2019-06-18 17:09:26',
            ),
            50 => 
            array (
                'id' => 51,
                'admission_student_id' => 51,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-19 12:26:15',
                'updated_at' => '2019-06-19 12:26:35',
            ),
            51 => 
            array (
                'id' => 52,
                'admission_student_id' => 52,
                'full_name' => 'Md Jewel Chowdhury',
                'relation' => NULL,
                'phone' => '01716393310',
                'email' => NULL,
            'address' => '56- Tantipara (Ground Floor)
Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-19 13:06:34',
                'updated_at' => '2019-06-19 13:06:54',
            ),
            52 => 
            array (
                'id' => 53,
                'admission_student_id' => 53,
                'full_name' => 'Md. Jalal Uddin',
                'relation' => NULL,
                'phone' => '01778126388',
                'email' => NULL,
                'address' => 'Charabhanga 
Itakhula 
Madhabpur, Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-20 11:08:01',
                'updated_at' => '2019-06-20 11:08:31',
            ),
            53 => 
            array (
                'id' => 54,
                'admission_student_id' => 54,
                'full_name' => 'Rubel Ahmed',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'Shahi Eidgah, sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 10:28:18',
                'updated_at' => '2019-06-22 10:28:44',
            ),
            54 => 
            array (
                'id' => 55,
                'admission_student_id' => 55,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 10:51:35',
                'updated_at' => '2019-06-22 10:51:53',
            ),
            55 => 
            array (
                'id' => 56,
                'admission_student_id' => 56,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 11:18:14',
                'updated_at' => '2019-06-22 11:18:53',
            ),
            56 => 
            array (
                'id' => 57,
                'admission_student_id' => 57,
                'full_name' => 'Ashutosh Singha',
                'relation' => NULL,
                'phone' => '01711983509',
                'email' => NULL,
                'address' => 'Vatalia, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 10:42:49',
                'updated_at' => '2019-06-23 10:46:34',
            ),
            57 => 
            array (
                'id' => 58,
                'admission_student_id' => 58,
                'full_name' => 'Mufti Moin Uddin',
                'relation' => NULL,
                'phone' => '01711950750',
                'email' => NULL,
                'address' => 'Dorgah Moholla, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 12:24:26',
                'updated_at' => '2019-06-23 12:24:55',
            ),
            58 => 
            array (
                'id' => 59,
                'admission_student_id' => 59,
                'full_name' => 'Bedana Begum',
                'relation' => 'Mother',
                'phone' => '01720078538',
                'email' => NULL,
                'address' => 'Vill: Nolbacid
PO: Nolbacid
PS: Sherpur
Sherpur',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 16:09:13',
                'updated_at' => '2019-06-23 16:16:27',
            ),
            59 => 
            array (
                'id' => 60,
                'admission_student_id' => 60,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 17:43:41',
                'updated_at' => '2019-06-23 17:44:16',
            ),
            60 => 
            array (
                'id' => 61,
                'admission_student_id' => 61,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-24 10:48:19',
                'updated_at' => '2019-06-24 10:49:07',
            ),
            61 => 
            array (
                'id' => 62,
                'admission_student_id' => 62,
                'full_name' => 'Mujibur Rahman',
                'relation' => NULL,
                'phone' => '01712172986',
                'email' => NULL,
                'address' => 'Vill: Raygor 
PO: Dhakadakshin
PS: Golapganj
Dist: Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-24 11:25:06',
                'updated_at' => '2019-06-25 12:14:54',
            ),
            62 => 
            array (
                'id' => 63,
                'admission_student_id' => 63,
                'full_name' => 'Md. Saiful Islam',
                'relation' => NULL,
                'phone' => '01718389089',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-24 12:31:37',
                'updated_at' => '2019-06-26 12:18:32',
            ),
            63 => 
            array (
                'id' => 64,
                'admission_student_id' => 64,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-24 13:22:31',
                'updated_at' => '2019-06-24 13:22:31',
            ),
            64 => 
            array (
                'id' => 65,
                'admission_student_id' => 65,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-24 14:19:58',
                'updated_at' => '2019-06-25 12:03:30',
            ),
            65 => 
            array (
                'id' => 66,
                'admission_student_id' => 66,
                'full_name' => 'Lipi Bhattacharjee',
                'relation' => 'N/A',
                'phone' => '01712109624',
                'email' => NULL,
            'address' => 'Shopnil 29/1, Ramerdighirpar (West Side)
Mirjajangal, Sylhet- 3100',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-25 10:35:15',
                'updated_at' => '2019-06-26 12:12:18',
            ),
            66 => 
            array (
                'id' => 67,
                'admission_student_id' => 67,
                'full_name' => 'Akter Hosen',
                'relation' => 'Brother',
                'phone' => '01741974369',
                'email' => NULL,
                'address' => 'Maa-Manzil
Block- A 
Nibas- 14
Modina Market, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-25 11:47:30',
                'updated_at' => '2019-06-29 11:11:35',
            ),
            67 => 
            array (
                'id' => 68,
                'admission_student_id' => 68,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-25 13:23:34',
                'updated_at' => '2019-06-25 13:23:34',
            ),
            68 => 
            array (
                'id' => 69,
                'admission_student_id' => 69,
                'full_name' => 'Dr. Sheikh Mohammad Misbah Uddin',
                'relation' => NULL,
                'phone' => '01733775300',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-26 10:25:31',
                'updated_at' => '2019-06-26 10:25:31',
            ),
            69 => 
            array (
                'id' => 70,
                'admission_student_id' => 70,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-26 11:04:52',
                'updated_at' => '2019-06-26 11:04:52',
            ),
            70 => 
            array (
                'id' => 71,
                'admission_student_id' => 71,
                'full_name' => 'Biplob Roy',
                'relation' => NULL,
                'phone' => '01730906030',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-26 11:23:52',
                'updated_at' => '2019-06-26 11:23:52',
            ),
            71 => 
            array (
                'id' => 72,
                'admission_student_id' => 72,
                'full_name' => 'Punit Yadab',
                'relation' => NULL,
                'phone' => '01716611060',
                'email' => NULL,
                'address' => 'Northeast Boy Hostel, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-30 12:19:48',
                'updated_at' => '2019-06-30 12:19:48',
            ),
            72 => 
            array (
                'id' => 73,
                'admission_student_id' => 73,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-30 13:23:12',
                'updated_at' => '2019-06-30 13:23:12',
            ),
            73 => 
            array (
                'id' => 74,
                'admission_student_id' => 74,
                'full_name' => 'Rajnesh Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NMEC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-18 11:14:05',
                'updated_at' => '2019-07-18 11:14:05',
            ),
            74 => 
            array (
                'id' => 75,
                'admission_student_id' => 75,
                'full_name' => 'Rainesh Yadav',
                'relation' => NULL,
                'phone' => '01727285916',
                'email' => NULL,
                'address' => 'NMEC Boy Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-18 13:17:43',
                'updated_at' => '2019-07-18 13:17:43',
            ),
            75 => 
            array (
                'id' => 76,
                'admission_student_id' => 76,
                'full_name' => 'Neraj Ali Shah',
                'relation' => NULL,
                'phone' => 'NEMC Boys Hostel',
                'email' => NULL,
                'address' => '01630870858',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 11:06:26',
                'updated_at' => '2019-07-20 11:06:26',
            ),
            76 => 
            array (
                'id' => 77,
                'admission_student_id' => 77,
                'full_name' => 'Rainish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 11:53:34',
                'updated_at' => '2019-07-20 11:53:34',
            ),
            77 => 
            array (
                'id' => 78,
                'admission_student_id' => 78,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 12:37:51',
                'updated_at' => '2019-07-20 12:37:51',
            ),
            78 => 
            array (
                'id' => 79,
                'admission_student_id' => 79,
                'full_name' => 'Rajneesh Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 13:04:53',
                'updated_at' => '2019-07-20 13:04:53',
            ),
            79 => 
            array (
                'id' => 80,
                'admission_student_id' => 80,
                'full_name' => 'Rajnesh Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-22 11:53:01',
                'updated_at' => '2019-07-22 11:53:01',
            ),
            80 => 
            array (
                'id' => 81,
                'admission_student_id' => 81,
                'full_name' => 'Rajnish',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-22 12:29:13',
                'updated_at' => '2019-07-22 12:29:13',
            ),
            81 => 
            array (
                'id' => 82,
                'admission_student_id' => 82,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-22 13:07:25',
                'updated_at' => '2019-07-22 13:07:25',
            ),
            82 => 
            array (
                'id' => 83,
                'admission_student_id' => 83,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boy Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 09:51:40',
                'updated_at' => '2019-07-24 09:51:40',
            ),
            83 => 
            array (
                'id' => 84,
                'admission_student_id' => 84,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 10:25:08',
                'updated_at' => '2019-07-24 10:25:08',
            ),
            84 => 
            array (
                'id' => 85,
                'admission_student_id' => 85,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 11:06:02',
                'updated_at' => '2019-07-24 11:06:02',
            ),
            85 => 
            array (
                'id' => 86,
                'admission_student_id' => 86,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 11:28:28',
                'updated_at' => '2019-07-24 11:28:28',
            ),
            86 => 
            array (
                'id' => 87,
                'admission_student_id' => 87,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 12:04:34',
                'updated_at' => '2019-07-24 12:04:34',
            ),
            87 => 
            array (
                'id' => 88,
                'admission_student_id' => 88,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 12:52:39',
                'updated_at' => '2019-07-24 12:52:39',
            ),
            88 => 
            array (
                'id' => 89,
                'admission_student_id' => 89,
                'full_name' => 'Rajnish',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 13:14:02',
                'updated_at' => '2019-07-24 13:14:02',
            ),
            89 => 
            array (
                'id' => 90,
                'admission_student_id' => 90,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 10:25:22',
                'updated_at' => '2019-07-25 10:25:22',
            ),
            90 => 
            array (
                'id' => 91,
                'admission_student_id' => 91,
                'full_name' => 'Birendra Kumar Shah',
                'relation' => NULL,
                'phone' => '01733988420',
                'email' => NULL,
                'address' => 'Siraha, Nepal',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 11:03:45',
                'updated_at' => '2019-07-25 11:03:45',
            ),
            91 => 
            array (
                'id' => 92,
                'admission_student_id' => 92,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 11:26:26',
                'updated_at' => '2019-07-25 11:26:26',
            ),
            92 => 
            array (
                'id' => 93,
                'admission_student_id' => 93,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 12:11:56',
                'updated_at' => '2019-08-05 11:46:39',
            ),
            93 => 
            array (
                'id' => 94,
                'admission_student_id' => 94,
                'full_name' => 'Bindo Pantha',
                'relation' => NULL,
                'phone' => '01918217600',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 12:55:55',
                'updated_at' => '2019-08-05 11:46:17',
            ),
            94 => 
            array (
                'id' => 95,
                'admission_student_id' => 95,
                'full_name' => 'Reshan shah',
                'relation' => NULL,
                'phone' => '01630985038',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 13:28:25',
                'updated_at' => '2019-08-05 11:45:48',
            ),
            95 => 
            array (
                'id' => 96,
                'admission_student_id' => 96,
                'full_name' => 'Adarsh Yadav',
                'relation' => NULL,
                'phone' => '01778569090',
                'email' => NULL,
                'address' => 'NEMC Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-31 12:31:50',
                'updated_at' => '2019-08-05 11:04:28',
            ),
            96 => 
            array (
                'id' => 97,
                'admission_student_id' => 97,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 11:29:54',
                'updated_at' => '2019-08-05 11:29:54',
            ),
            97 => 
            array (
                'id' => 98,
                'admission_student_id' => 98,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 11:39:18',
                'updated_at' => '2019-08-05 11:39:18',
            ),
            98 => 
            array (
                'id' => 99,
                'admission_student_id' => 99,
                'full_name' => 'Anushka Thapa',
                'relation' => NULL,
                'phone' => '01192254550',
                'email' => NULL,
                'address' => 'NEMC Girls Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 12:01:10',
                'updated_at' => '2019-08-05 12:01:10',
            ),
            99 => 
            array (
                'id' => 100,
                'admission_student_id' => 100,
                'full_name' => 'Ocean Magar',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 10:07:54',
                'updated_at' => '2019-08-07 10:07:54',
            ),
            100 => 
            array (
                'id' => 101,
                'admission_student_id' => 101,
                'full_name' => 'Punit Yadav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'NEMC',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 10:36:06',
                'updated_at' => '2019-08-07 10:36:06',
            ),
            101 => 
            array (
                'id' => 102,
                'admission_student_id' => 102,
                'full_name' => 'Aman Yadav',
                'relation' => NULL,
                'phone' => '01792382241',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 12:51:26',
                'updated_at' => '2019-08-07 12:51:26',
            ),
            102 => 
            array (
                'id' => 103,
                'admission_student_id' => 103,
                'full_name' => 'Shree Kumar Shrestha',
                'relation' => NULL,
                'phone' => '016219980954',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 13:15:35',
                'updated_at' => '2019-08-07 13:15:35',
            ),
            103 => 
            array (
                'id' => 104,
                'admission_student_id' => 104,
                'full_name' => 'Rupnarayan Mandal',
                'relation' => NULL,
                'phone' => '01781878946',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 13:33:25',
                'updated_at' => '2019-08-07 13:33:25',
            ),
            104 => 
            array (
                'id' => 105,
                'admission_student_id' => 105,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 10:09:27',
                'updated_at' => '2019-08-08 10:09:27',
            ),
            105 => 
            array (
                'id' => 106,
                'admission_student_id' => 106,
                'full_name' => 'Ravi Rauniyar',
                'relation' => NULL,
                'phone' => '0170598587',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 10:46:22',
                'updated_at' => '2019-08-08 10:46:22',
            ),
            106 => 
            array (
                'id' => 107,
                'admission_student_id' => 107,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 11:14:32',
                'updated_at' => '2019-08-08 11:14:32',
            ),
            107 => 
            array (
                'id' => 108,
                'admission_student_id' => 108,
                'full_name' => 'Aman Yadav',
                'relation' => NULL,
                'phone' => '01792382241',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 11:39:16',
                'updated_at' => '2019-08-08 11:39:16',
            ),
            108 => 
            array (
                'id' => 109,
                'admission_student_id' => 109,
                'full_name' => 'Gaurav Subedi',
                'relation' => NULL,
                'phone' => '01732075040',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 11:57:03',
                'updated_at' => '2019-08-08 11:57:03',
            ),
            109 => 
            array (
                'id' => 110,
                'admission_student_id' => 110,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 12:15:53',
                'updated_at' => '2019-08-08 12:15:53',
            ),
            110 => 
            array (
                'id' => 111,
                'admission_student_id' => 111,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 12:31:20',
                'updated_at' => '2019-08-08 12:31:20',
            ),
            111 => 
            array (
                'id' => 112,
                'admission_student_id' => 112,
                'full_name' => 'Rajib Yadav',
                'relation' => NULL,
                'phone' => '01855717591',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-10 10:12:16',
                'updated_at' => '2019-08-10 10:12:16',
            ),
            112 => 
            array (
                'id' => 113,
                'admission_student_id' => 113,
                'full_name' => 'Rupnarayan Mandal',
                'relation' => NULL,
                'phone' => '01781878946',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-10 10:30:56',
                'updated_at' => '2019-08-10 10:31:28',
            ),
            113 => 
            array (
                'id' => 114,
                'admission_student_id' => 114,
                'full_name' => 'Suresh Kumar Yadav',
                'relation' => NULL,
                'phone' => '01792255236',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-10 11:25:59',
                'updated_at' => '2019-08-10 11:25:59',
            ),
            114 => 
            array (
                'id' => 115,
                'admission_student_id' => 115,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-10 12:23:03',
                'updated_at' => '2019-08-10 12:23:03',
            ),
            115 => 
            array (
                'id' => 116,
                'admission_student_id' => 116,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-17 10:36:48',
                'updated_at' => '2019-08-17 10:36:48',
            ),
            116 => 
            array (
                'id' => 117,
                'admission_student_id' => 117,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-17 11:02:20',
                'updated_at' => '2019-08-17 11:02:20',
            ),
            117 => 
            array (
                'id' => 118,
                'admission_student_id' => 118,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-17 11:31:39',
                'updated_at' => '2019-08-17 11:31:39',
            ),
            118 => 
            array (
                'id' => 119,
                'admission_student_id' => 119,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-17 11:59:19',
                'updated_at' => '2019-08-17 11:59:19',
            ),
            119 => 
            array (
                'id' => 120,
                'admission_student_id' => 120,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-17 12:42:07',
                'updated_at' => '2019-08-17 12:42:07',
            ),
            120 => 
            array (
                'id' => 121,
                'admission_student_id' => 121,
                'full_name' => 'Dr. Niroj Karki',
                'relation' => NULL,
                'phone' => '01721370114',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-19 12:09:58',
                'updated_at' => '2019-08-19 12:09:58',
            ),
            121 => 
            array (
                'id' => 122,
                'admission_student_id' => 122,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-19 12:30:14',
                'updated_at' => '2019-08-19 12:30:14',
            ),
            122 => 
            array (
                'id' => 123,
                'admission_student_id' => 123,
                'full_name' => 'Subash Chandra Yadav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-19 13:02:37',
                'updated_at' => '2019-08-19 13:02:37',
            ),
            123 => 
            array (
                'id' => 124,
                'admission_student_id' => 124,
                'full_name' => 'Sameer Shrivastav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-19 13:32:59',
                'updated_at' => '2019-08-19 13:32:59',
            ),
            124 => 
            array (
                'id' => 125,
                'admission_student_id' => 125,
                'full_name' => 'Sameer Srivastav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-19 14:30:33',
                'updated_at' => '2019-08-19 14:30:33',
            ),
            125 => 
            array (
                'id' => 126,
                'admission_student_id' => 126,
                'full_name' => 'Punit Yadav',
                'relation' => NULL,
                'phone' => '01766177800',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 10:39:55',
                'updated_at' => '2019-08-20 10:39:55',
            ),
            126 => 
            array (
                'id' => 127,
                'admission_student_id' => 127,
                'full_name' => 'Dr. Saddam Ansari',
                'relation' => NULL,
                'phone' => '01792254031',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 11:13:09',
                'updated_at' => '2019-08-20 11:13:09',
            ),
            127 => 
            array (
                'id' => 128,
                'admission_student_id' => 128,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 11:40:02',
                'updated_at' => '2019-08-20 11:40:02',
            ),
            128 => 
            array (
                'id' => 129,
                'admission_student_id' => 129,
                'full_name' => 'MD. Saddam Ansari',
                'relation' => NULL,
                'phone' => '01792254031',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 12:18:05',
                'updated_at' => '2019-08-20 12:26:57',
            ),
            129 => 
            array (
                'id' => 130,
                'admission_student_id' => 130,
                'full_name' => 'Bhupendra das',
                'relation' => NULL,
                'phone' => '01998848729',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 12:35:34',
                'updated_at' => '2019-08-20 12:35:34',
            ),
            130 => 
            array (
                'id' => 131,
                'admission_student_id' => 131,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 12:51:55',
                'updated_at' => '2019-08-20 12:51:55',
            ),
        ));
        
        
    }
}