<?php

use Illuminate\Database\Seeder;

class AdminUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('admin_users')->delete();
        
        \DB::table('admin_users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 1,
                'department_id' => NULL,
                'designation_id' => 2,
                'course_id' => NULL,
                'full_name' => 'Manajjir Ali',
                'email' => 'admin@nemc.com',
                'address' => NULL,
                'phone' => '01711112233',
                'photo' => NULL,
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'user_id' => 336,
                'department_id' => 1,
                'designation_id' => 14,
                'course_id' => 1,
                'full_name' => 'Md Abdul Wahid',
                'email' => 'wahidnemc@gmail.com',
                'address' => NULL,
                'phone' => '01711059790',
                'photo' => 'nemc_files/users/1571812701_Md. Abdul Wahid-30001201.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 09:48:03',
                'updated_at' => '2019-10-23 12:38:27',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'user_id' => 337,
                'department_id' => 2,
                'designation_id' => 15,
                'course_id' => 1,
                'full_name' => 'A.K.M. Luthful Haque Chowdhury',
                'email' => 'mba.0803010504@gmail.com',
                'address' => NULL,
                'phone' => '01717932000',
                'photo' => 'nemc_files/users/1571630106_Photo.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 09:55:40',
                'updated_at' => '2019-10-21 09:55:40',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'user_id' => 338,
                'department_id' => 28,
                'designation_id' => 16,
                'course_id' => 1,
                'full_name' => 'Syed Istiaque Ahmed',
                'email' => 'istiaque.nempl@gmail.com',
                'address' => NULL,
                'phone' => '01730300664',
                'photo' => NULL,
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:06:39',
                'updated_at' => '2019-10-21 10:06:39',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'user_id' => 339,
                'department_id' => 28,
                'designation_id' => 17,
                'course_id' => 1,
                'full_name' => 'Oli Hammad Ahmed Chowdhury',
                'email' => 'hammad_chy@yahoo.com',
                'address' => NULL,
                'phone' => '01714362204',
                'photo' => 'nemc_files/users/1571812186_Hammad.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:14:26',
                'updated_at' => '2019-10-23 12:29:56',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'user_id' => 340,
                'department_id' => 2,
                'designation_id' => 18,
                'course_id' => 1,
                'full_name' => 'Shah Md. Sharful Abedin',
                'email' => 'sharful77@gmail.com',
                'address' => NULL,
                'phone' => '01632980523',
                'photo' => NULL,
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:21:55',
                'updated_at' => '2019-10-21 10:21:55',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'user_id' => 341,
                'department_id' => 2,
                'designation_id' => 19,
                'course_id' => 1,
                'full_name' => 'Sumon Hasan',
                'email' => NULL,
                'address' => NULL,
                'phone' => '01712746005',
                'photo' => NULL,
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:27:31',
                'updated_at' => '2019-10-21 10:27:31',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'user_id' => 342,
                'department_id' => 2,
                'designation_id' => 19,
                'course_id' => 1,
                'full_name' => 'Shahedur Rahman',
                'email' => 'kironrahman71@gmail.com',
                'address' => NULL,
                'phone' => '01734003959',
                'photo' => 'nemc_files/users/1571632344_Photo.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:32:42',
                'updated_at' => '2019-10-21 10:32:42',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'user_id' => 343,
                'department_id' => 1,
                'designation_id' => 20,
                'course_id' => 2,
                'full_name' => 'Mohammed Mozammel Hoque',
                'email' => 'mhbahar@yahoo.com',
                'address' => NULL,
                'phone' => '01716465539',
                'photo' => 'nemc_files/users/1571632603_Mozammel.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:36:50',
                'updated_at' => '2019-10-21 10:36:50',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'user_id' => 344,
                'department_id' => 28,
                'designation_id' => 18,
                'course_id' => 2,
                'full_name' => 'Md. Tarek Rahman',
                'email' => 'tarek.rahman@ymail.com',
                'address' => NULL,
                'phone' => '01716817857',
                'photo' => 'nemc_files/users/1571632898_Photo.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-21 10:41:43',
                'updated_at' => '2019-10-21 10:41:43',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'user_id' => 345,
                'department_id' => 3,
                'designation_id' => 21,
                'course_id' => NULL,
                'full_name' => 'Ashim Das',
                'email' => 'ashim.nemch@gmail.com',
                'address' => NULL,
                'phone' => '01711700586',
                'photo' => 'nemc_files/users/1571810670_download.png',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-23 11:58:15',
                'updated_at' => '2019-10-23 12:04:38',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'user_id' => 346,
                'department_id' => 3,
                'designation_id' => 22,
                'course_id' => NULL,
                'full_name' => 'Saheli Begum',
                'email' => 'saheli.nemc@gmail.com',
                'address' => NULL,
                'phone' => 'admin@nemc.com',
                'photo' => 'nemc_files/users/1571810559_Photo.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-23 12:02:46',
                'updated_at' => '2019-10-23 12:02:46',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'user_id' => 347,
                'department_id' => 3,
                'designation_id' => 23,
                'course_id' => NULL,
                'full_name' => 'Khasrul Hoque',
                'email' => 'khasrummu@gmail.com',
                'address' => NULL,
                'phone' => '01911199990',
                'photo' => 'nemc_files/users/1571810815_DSC_4591 pp.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-23 12:07:03',
                'updated_at' => '2019-10-23 12:31:31',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'user_id' => 348,
                'department_id' => 28,
                'designation_id' => 24,
                'course_id' => 1,
                'full_name' => 'Md. Sirajul Islam Chowdhury',
                'email' => 'sirajnemc@gmail.com',
                'address' => NULL,
                'phone' => '01712623077',
                'photo' => 'nemc_files/users/1571812564_Siraj.jpg',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-10-23 12:36:36',
                'updated_at' => '2019-10-23 12:37:45',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}