<?php

use Illuminate\Database\Seeder;

class BanksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('banks')->delete();

        \DB::table('banks')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'title' => 'AB Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            1 =>
                array (
                    'id' => 2,
                    'title' => 'Agrani Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            2 =>
                array (
                    'id' => 3,
                    'title' => 'Al-Arafah Islami Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            3 =>
                array (
                    'id' => 4,
                    'title' => 'Bangladesh Commerce Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            4 =>
                array (
                    'id' => 5,
                    'title' => 'Bangladesh Development Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            5 =>
                array (
                    'id' => 6,
                    'title' => 'Bangladesh Krishi Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            6 =>
                array (
                    'id' => 7,
                    'title' => 'Bank Al-Falah Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            7 =>
                array (
                    'id' => 8,
                    'title' => 'Bank Asia Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            8 =>
                array (
                    'id' => 9,
                    'title' => 'BASIC Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            9 =>
                array (
                    'id' => 10,
                    'title' => 'BRAC Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            10 =>
                array (
                    'id' => 11,
                    'title' => 'Citibank N.A',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            11 =>
                array (
                    'id' => 12,
                    'title' => 'Commercial Bank of Ceylon Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            12 =>
                array (
                    'id' => 13,
                    'title' => 'Dhaka Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            13 =>
                array (
                    'id' => 14,
                    'title' => 'Dutch-Bangla Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            14 =>
                array (
                    'id' => 15,
                    'title' => 'Eastern Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            15 =>
                array (
                    'id' => 16,
                    'title' => 'EXIM Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            16 =>
                array (
                    'id' => 17,
                    'title' => 'First Security Islami Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            17 =>
                array (
                    'id' => 18,
                    'title' => 'Habib Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            18 =>
                array (
                    'id' => 19,
                    'title' => 'ICB Islamic Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            19 =>
                array (
                    'id' => 20,
                    'title' => 'IFIC Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            20 =>
                array (
                    'id' => 21,
                    'title' => 'Islami Bank Bangladesh Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            21 =>
                array (
                    'id' => 22,
                    'title' => 'Jamuna Bank Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            22 =>
                array (
                    'id' => 23,
                    'title' => 'Janata Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            23 =>
                array (
                    'id' => 24,
                    'title' => 'Meghna Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            24 =>
                array (
                    'id' => 25,
                    'title' => 'Mercantile Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            25 =>
                array (
                    'id' => 26,
                    'title' => 'Midland Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            26 =>
                array (
                    'id' => 27,
                    'title' => 'Modhumoti Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            27 =>
                array (
                    'id' => 28,
                    'title' => 'Mutual Trust Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            28 =>
                array (
                    'id' => 29,
                    'title' => 'National Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            29 =>
                array (
                    'id' => 30,
                    'title' => 'National Bank of Pakistan',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            30 =>
                array (
                    'id' => 31,
                    'title' => 'National Credit & Commerce Bank Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            31 =>
                array (
                    'id' => 32,
                    'title' => 'NRB Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            32 =>
                array (
                    'id' => 33,
                    'title' => 'NRB Commercial Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            33 =>
                array (
                    'id' => 34,
                    'title' => 'NRB Global Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            34 =>
                array (
                    'id' => 35,
                    'title' => 'One Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            35 =>
                array (
                    'id' => 36,
                    'title' => 'Padma Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            36 =>
                array (
                    'id' => 37,
                    'title' => 'Palli Sanchay Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            37 =>
                array (
                    'id' => 38,
                    'title' => 'Premier Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            38 =>
                array (
                    'id' => 39,
                    'title' => 'Prime Bank Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            39 =>
                array (
                    'id' => 40,
                    'title' => 'Probashi Kollyan Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            40 =>
                array (
                    'id' => 41,
                    'title' => 'Pubali Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            41 =>
                array (
                    'id' => 42,
                    'title' => 'Rupali Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            42 =>
                array (
                    'id' => 43,
                    'title' => 'Shahjalal Islami Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            43 =>
                array (
                    'id' => 44,
                    'title' => 'Shimanto Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            44 =>
                array (
                    'id' => 45,
                    'title' => 'Social Islami Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            45 =>
                array (
                    'id' => 46,
                    'title' => 'Sonali Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            46 =>
                array (
                    'id' => 47,
                    'title' => 'South Bangla Agriculture & Commerce Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            47 =>
                array (
                    'id' => 48,
                    'title' => 'Southeast Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            48 =>
                array (
                    'id' => 49,
                    'title' => 'Standard Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            49 =>
                array (
                    'id' => 50,
                    'title' => 'Standard Chartered Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            50 =>
                array (
                    'id' => 51,
                    'title' => 'State Bank of India',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            51 =>
                array (
                    'id' => 52,
                    'title' => 'The City Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            52 =>
                array (
                    'id' => 53,
                    'title' => 'The Hong Kong and Shanghai Banking Corporation. Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            53 =>
                array (
                    'id' => 54,
                    'title' => 'Trust Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            54 =>
                array (
                    'id' => 55,
                    'title' => 'Union Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            55 =>
                array (
                    'id' => 56,
                    'title' => 'United Commercial Bank  Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            56 =>
                array (
                    'id' => 57,
                    'title' => 'Uttara Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            57 =>
                array (
                    'id' => 58,
                    'title' => 'Woori Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            58 =>
                array (
                    'id' => 59,
                    'title' => 'AB Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            59 =>
                array (
                    'id' => 60,
                    'title' => 'Agrani Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            60 =>
                array (
                    'id' => 61,
                    'title' => 'Al-Arafah Islami Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            61 =>
                array (
                    'id' => 62,
                    'title' => 'Bangladesh Development Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            62 =>
                array (
                    'id' => 63,
                    'title' => 'Bangladesh Krishi Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            63 =>
                array (
                    'id' => 64,
                    'title' => 'Bank Al-Falah Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            64 =>
                array (
                    'id' => 65,
                    'title' => 'Bank Asia Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            65 =>
                array (
                    'id' => 66,
                    'title' => 'BASIC Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            66 =>
                array (
                    'id' => 67,
                    'title' => 'BRAC Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            67 =>
                array (
                    'id' => 68,
                    'title' => 'Citibank N.A',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            68 =>
                array (
                    'id' => 69,
                    'title' => 'Commercial Bank of Ceylon Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            69 =>
                array (
                    'id' => 70,
                    'title' => 'Dhaka Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            70 =>
                array (
                    'id' => 71,
                    'title' => 'Dutch-Bangla Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            71 =>
                array (
                    'id' => 72,
                    'title' => 'Eastern Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            72 =>
                array (
                    'id' => 73,
                    'title' => 'EXIM Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            73 =>
                array (
                    'id' => 74,
                    'title' => 'First Security Islami Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            74 =>
                array (
                    'id' => 75,
                    'title' => 'Habib Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            75 =>
                array (
                    'id' => 76,
                    'title' => 'ICB Islamic Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            76 =>
                array (
                    'id' => 77,
                    'title' => 'IFIC Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            77 =>
                array (
                    'id' => 78,
                    'title' => 'Islami Bank Bangladesh Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            78 =>
                array (
                    'id' => 79,
                    'title' => 'Jamuna Bank Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            79 =>
                array (
                    'id' => 80,
                    'title' => 'Janata Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            80 =>
                array (
                    'id' => 81,
                    'title' => 'Meghna Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            81 =>
                array (
                    'id' => 82,
                    'title' => 'Mercantile Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            82 =>
                array (
                    'id' => 83,
                    'title' => 'Midland Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            83 =>
                array (
                    'id' => 84,
                    'title' => 'Modhumoti Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            84 =>
                array (
                    'id' => 85,
                    'title' => 'Mutual Trust Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            85 =>
                array (
                    'id' => 86,
                    'title' => 'National Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            86 =>
                array (
                    'id' => 87,
                    'title' => 'National Bank of Pakistan',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            87 =>
                array (
                    'id' => 88,
                    'title' => 'National Credit & Commerce Bank Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            88 =>
                array (
                    'id' => 89,
                    'title' => 'NRB Commercial Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            89 =>
                array (
                    'id' => 90,
                    'title' => 'NRB Global Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            90 =>
                array (
                    'id' => 91,
                    'title' => 'One Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            91 =>
                array (
                    'id' => 92,
                    'title' => 'Padma Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            92 =>
                array (
                    'id' => 93,
                    'title' => 'Palli Sanchay Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            93 =>
                array (
                    'id' => 94,
                    'title' => 'Premier Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            94 =>
                array (
                    'id' => 95,
                    'title' => 'Prime Bank Ltd',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            95 =>
                array (
                    'id' => 96,
                    'title' => 'Probashi Kollyan Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            96 =>
                array (
                    'id' => 97,
                    'title' => 'Pubali Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            97 =>
                array (
                    'id' => 98,
                    'title' => 'Rajshahi Krishi Unnayan Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            98 =>
                array (
                    'id' => 99,
                    'title' => 'Rupali Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            99 =>
                array (
                    'id' => 100,
                    'title' => 'Shahjalal Islami Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            100 =>
                array (
                    'id' => 101,
                    'title' => 'Shimanto Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            101 =>
                array (
                    'id' => 102,
                    'title' => 'Social Islami Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            102 =>
                array (
                    'id' => 103,
                    'title' => 'Sonali Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            103 =>
                array (
                    'id' => 104,
                    'title' => 'South Bangla Agriculture & Commerce Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            104 =>
                array (
                    'id' => 105,
                    'title' => 'Southeast Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            105 =>
                array (
                    'id' => 106,
                    'title' => 'Standard Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            106 =>
                array (
                    'id' => 107,
                    'title' => 'Standard Chartered Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            107 =>
                array (
                    'id' => 108,
                    'title' => 'State Bank of India',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            108 =>
                array (
                    'id' => 109,
                    'title' => 'The City Bank Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            109 =>
                array (
                    'id' => 110,
                    'title' => 'The Hong Kong and Shanghai Banking Corporation. Ltd.',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            110 =>
                array (
                    'id' => 111,
                    'title' => 'Trust Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            111 =>
                array (
                    'id' => 112,
                    'title' => 'Union Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            112 =>
                array (
                    'id' => 113,
                    'title' => 'United Commercial Bank  Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            113 =>
                array (
                    'id' => 114,
                    'title' => 'Uttara Bank Limited',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            114 =>
                array (
                    'id' => 115,
                    'title' => 'Woori Bank',
                    'status' => 1,
                    'created_by' => NULL,
                    'updated_by' => NULL,
                    'created_at' => '2019-05-14 15:46:34',
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
        ));


    }
}
