<?php

use Illuminate\Database\Seeder;

class CardsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('cards')->delete();
        
        \DB::table('cards')->insert(array (
            0 => 
            array (
                'id' => 1,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'ELEMENTARY BIOCHEMISTRY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 13:04:43',
                'updated_at' => '2019-06-22 13:04:43',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'FOOD & NUTRITION',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 13:20:38',
                'updated_at' => '2019-06-22 13:20:38',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'DIGESTION & ABSORPTION OF BIOMOLECULES',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 11:46:22',
                'updated_at' => '2019-06-23 11:46:22',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'METABOLISM & BIOENERGETIC',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 11:47:51',
                'updated_at' => '2019-06-23 11:47:51',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'RENAL BIOCHEMISTRY, BODY FLUID, ELECTROLYTES AND ACID-BASE BALANCE',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-06-23 11:49:01',
                'updated_at' => '2019-06-23 11:50:11',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'CLINICAL ENDOCRINOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 12:11:50',
                'updated_at' => '2019-06-23 12:11:50',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'CLINICAL BIOCHEMISTRY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 12:12:34',
                'updated_at' => '2019-06-23 12:12:34',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'MOLECULAR BIOLOGY & GENETICS',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 12:13:33',
                'updated_at' => '2019-06-23 12:13:33',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'subject_id' => 3,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'BIOCHEMISTRY PRACTICAL',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 12:16:41',
                'updated_at' => '2019-06-23 12:16:41',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'subject_id' => 1,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'THORAX CARD',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-28 11:27:43',
                'updated_at' => '2019-08-28 11:27:43',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'subject_id' => 1,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'SUPERIOR EXTREMITY CARD',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-28 11:52:00',
                'updated_at' => '2019-08-28 11:52:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'subject_id' => 1,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'ABDOMEN CARD',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-28 12:00:17',
                'updated_at' => '2019-08-28 12:00:17',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'subject_id' => 1,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'INFERIOR EXTREMITY CARD',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-28 12:12:42',
                'updated_at' => '2019-08-28 12:12:42',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'subject_id' => 1,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'HEAD & NECK CARD',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-28 12:16:16',
                'updated_at' => '2019-08-28 12:16:16',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 1,
                'title' => 'GENERAL BACTERIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 12:55:41',
                'updated_at' => '2019-08-29 11:04:14',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 1,
                'title' => 'SYSTEMIC BACTERIOLOGY',
                'description' => '<p><br></p>',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 13:05:07',
                'updated_at' => '2019-08-29 11:03:45',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 1,
                'title' => 'IMMUNOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 13:15:28',
                'updated_at' => '2019-08-29 11:04:05',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 2,
                'title' => 'PARASITOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 13:26:57',
                'updated_at' => '2019-08-29 11:03:51',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 2,
                'title' => 'VIROLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 13:29:57',
                'updated_at' => '2019-08-29 11:03:37',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 2,
                'title' => 'MYCOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 13:59:22',
                'updated_at' => '2019-08-29 11:03:56',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'subject_id' => 8,
                'phase_id' => 3,
                'term_id' => 2,
                'title' => 'CLINICAL MICROBIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-08-28 13:59:50',
                'updated_at' => '2019-08-29 11:04:21',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'CELLULAR PHYSIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:33:27',
                'updated_at' => '2019-08-29 09:33:27',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'BLOOD',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:40:39',
                'updated_at' => '2019-08-29 09:40:39',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 1,
                'title' => 'CARDIOVASCULAR PHYSIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:47:18',
                'updated_at' => '2019-08-29 09:47:18',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'RESPIRATORY PHYSIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:50:08',
                'updated_at' => '2019-08-29 09:50:08',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'GASTROINTESTINAL PHYSIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:54:00',
                'updated_at' => '2019-08-29 09:54:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 2,
                'title' => 'RENAL PHYSIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:57:39',
                'updated_at' => '2019-08-29 09:57:39',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'ENDOCRINE PHYSIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 09:59:57',
                'updated_at' => '2019-08-29 09:59:57',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'PHYSIOLOGY OF REPRODUCTION',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 10:02:40',
                'updated_at' => '2019-08-29 10:02:40',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'subject_id' => 2,
                'phase_id' => 1,
                'term_id' => 3,
                'title' => 'NEUROPHYSIOLOGY & SPECIAL SENSES',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 10:06:34',
                'updated_at' => '2019-08-29 10:06:34',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 1,
                'title' => 'BASIC CONCEPT OF COMMUNITY MEDICINE',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:11:09',
                'updated_at' => '2019-08-29 11:11:09',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 1,
                'title' => 'FAMILY PLANNING & DEMOGRAPHY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:14:06',
                'updated_at' => '2019-08-29 11:14:06',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 1,
                'title' => 'IMMUNITY, DISINFECTION & EPIDEMIOLOGY',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:23:48',
                'updated_at' => '2019-08-29 11:23:48',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 1,
                'title' => 'HEALTH EDUCATION & COMMUNICATION, OCCUPATIONAL HEALTH AND BIOSTASTISTICS',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:25:25',
                'updated_at' => '2019-08-29 11:25:25',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 1,
                'title' => 'MCH & SCHOOL HEALTH SERVICES',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:27:15',
                'updated_at' => '2019-08-29 11:27:15',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 2,
                'title' => 'ENVIRONMENTAL HEALTH, DISASTER & SCREENING',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:29:59',
                'updated_at' => '2019-08-29 11:29:59',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 2,
                'title' => 'MEDICAL ENTOMOLOGY AND NATIONAL & INTERNATIONAL HEALTH ORGANIZATION',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:32:13',
                'updated_at' => '2019-08-29 11:32:13',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 2,
                'title' => 'FOOD & NUTRITION',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:34:28',
                'updated_at' => '2019-08-29 11:34:28',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'subject_id' => 4,
                'phase_id' => 2,
                'term_id' => 2,
                'title' => 'COMMUNICABLE & NON-COMMUNICABLE DISEASES AND BEHAVIOURAL SCIENCE',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-29 11:36:18',
                'updated_at' => '2019-08-29 11:36:18',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'subject_id' => 7,
                'phase_id' => 3,
                'term_id' => 1,
                'title' => 'A. General Pathology',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-31 11:31:42',
                'updated_at' => '2019-08-31 11:31:42',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'subject_id' => 7,
                'phase_id' => 3,
                'term_id' => 1,
            'title' => 'B: Systemic Pathology (I)',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-31 12:38:13',
                'updated_at' => '2019-08-31 12:38:13',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'subject_id' => 7,
                'phase_id' => 3,
                'term_id' => 2,
            'title' => 'Systemic Pathology (II)',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-31 13:05:08',
                'updated_at' => '2019-08-31 13:05:08',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'subject_id' => 5,
                'phase_id' => 2,
                'term_id' => 1,
                'title' => 'Forensic Medline',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-09-11 12:37:15',
                'updated_at' => '2019-09-11 12:53:13',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'subject_id' => 5,
                'phase_id' => 2,
                'term_id' => 2,
                'title' => 'Toxicology',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2019-09-11 12:42:39',
                'updated_at' => '2019-09-11 12:53:46',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'subject_id' => 6,
                'phase_id' => 3,
                'term_id' => 1,
                'title' => 'General Pharmacology',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-09-11 12:57:06',
                'updated_at' => '2019-09-11 12:57:06',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'subject_id' => 6,
                'phase_id' => 3,
                'term_id' => 2,
                'title' => 'Systemic Pharmacology',
                'description' => NULL,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-09-11 13:01:50',
                'updated_at' => '2019-09-11 13:01:50',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}