<?php

use Illuminate\Database\Seeder;

class EmergencyContactsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('emergency_contacts')->delete();
        
        \DB::table('emergency_contacts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'student_id' => 4,
                'full_name' => 'Mrs. Hena Begum',
                'relation' => 'Mother',
                'phone' => '01711120033',
                'email' => NULL,
                'address' => 'Chunarughat, Habiganj.',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:09:35',
                'updated_at' => '2019-06-27 11:12:39',
            ),
            1 => 
            array (
                'id' => 2,
                'student_id' => 5,
                'full_name' => 'Md. Taj Uddin',
                'relation' => NULL,
                'phone' => '01711445056',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:21:24',
                'updated_at' => '2019-06-27 11:25:51',
            ),
            2 => 
            array (
                'id' => 3,
                'student_id' => 6,
                'full_name' => 'Mst. Amina Begum',
                'relation' => 'Mother',
                'phone' => '01748464302',
                'email' => NULL,
                'address' => 'Nalbohor.
Beanibazar, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:22:14',
                'updated_at' => '2019-06-27 11:27:33',
            ),
            3 => 
            array (
                'id' => 4,
                'student_id' => 7,
                'full_name' => 'Dr. Sawjia Islam Amin',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'NEMC Girls Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:27:51',
                'updated_at' => '2019-06-27 11:31:33',
            ),
            4 => 
            array (
                'id' => 5,
                'student_id' => 8,
                'full_name' => 'Md. Abdul Wahid',
                'relation' => NULL,
                'phone' => '01711059790',
                'email' => NULL,
                'address' => 'NEMC Secretary',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:29:15',
                'updated_at' => '2019-06-27 11:36:44',
            ),
            5 => 
            array (
                'id' => 6,
                'student_id' => 9,
                'full_name' => 'Mst. Sheuli Begum',
                'relation' => 'Mother',
                'phone' => '01745705683',
                'email' => NULL,
                'address' => 'Jalalabad, Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:30:14',
                'updated_at' => '2019-06-27 11:37:46',
            ),
            6 => 
            array (
                'id' => 7,
                'student_id' => 10,
                'full_name' => 'Syeda Luna Akther',
                'relation' => 'Mother',
                'phone' => '01741089684',
                'email' => NULL,
                'address' => 'Chunarughat, Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:33:57',
                'updated_at' => '2019-06-27 11:40:11',
            ),
            7 => 
            array (
                'id' => 8,
                'student_id' => 11,
                'full_name' => 'Abdul Mutlib',
                'relation' => 'Father',
                'phone' => '01715525165',
                'email' => NULL,
                'address' => 'House No. 1 
Block- A 
Gutatikor R/A 
PO: Kodomtali, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:35:00',
                'updated_at' => '2019-06-27 11:42:10',
            ),
            8 => 
            array (
                'id' => 9,
                'student_id' => 12,
                'full_name' => 'Pritush Mohon Datta',
                'relation' => 'Father',
                'phone' => '01749863012',
                'email' => NULL,
                'address' => 'Pritom Medicine House
Srimongal Road, Moulovi Bazar',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:36:09',
                'updated_at' => '2019-06-27 11:44:34',
            ),
            9 => 
            array (
                'id' => 10,
                'student_id' => 13,
                'full_name' => 'Dr. Bashir Uddin, Assistant Professor NEMC',
                'relation' => NULL,
                'phone' => '01794153543',
                'email' => NULL,
                'address' => 'NEMC',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:37:12',
                'updated_at' => '2019-06-27 11:47:33',
            ),
            10 => 
            array (
                'id' => 11,
                'student_id' => 14,
                'full_name' => 'Imran Mahmud Shahjahan',
                'relation' => 'Brother',
                'phone' => '01747685882',
                'email' => NULL,
                'address' => 'Rangdhanu 1/A
Lakhripara
Shibganj, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 12:49:55',
                'updated_at' => '2019-06-27 11:52:38',
            ),
            11 => 
            array (
                'id' => 12,
                'student_id' => 15,
                'full_name' => 'Amith Deb Joy',
                'relation' => NULL,
                'phone' => '01759032187',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-28 13:35:47',
                'updated_at' => '2019-06-27 11:54:16',
            ),
            12 => 
            array (
                'id' => 13,
                'student_id' => 16,
                'full_name' => 'Umadur Rahman',
                'relation' => NULL,
                'phone' => '01712030654',
                'email' => NULL,
                'address' => 'Jalalabad Cantonment, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:37:53',
                'updated_at' => '2019-06-29 11:02:07',
            ),
            13 => 
            array (
                'id' => 14,
                'student_id' => 17,
                'full_name' => 'Muss. Hawarun Nessa Khanom',
                'relation' => 'Mother',
                'phone' => '017100716167',
                'email' => NULL,
                'address' => 'Focus- 105 
Uttar Baluchar, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:38:39',
                'updated_at' => '2019-06-29 11:03:45',
            ),
            14 => 
            array (
                'id' => 15,
                'student_id' => 18,
                'full_name' => 'Sheikh Monu Miah',
                'relation' => 'Father',
                'phone' => '01737303738',
                'email' => NULL,
                'address' => 'Konirchok, Porgona Bazar
Shahporan, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:39:11',
                'updated_at' => '2019-06-23 17:58:54',
            ),
            15 => 
            array (
                'id' => 16,
                'student_id' => 19,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:39:54',
                'updated_at' => '2019-06-23 17:49:57',
            ),
            16 => 
            array (
                'id' => 17,
                'student_id' => 20,
                'full_name' => 'Mohibul goni Panna',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'Shapla Kuthir
House No. 90 
Kazitula Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:41:47',
                'updated_at' => '2019-06-23 17:52:11',
            ),
            17 => 
            array (
                'id' => 18,
                'student_id' => 21,
                'full_name' => 'Amullya Kumar Ghosh',
                'relation' => 'father',
                'phone' => '01714458257',
                'email' => NULL,
                'address' => 'Kubjhar
PO: Ghorgoan
PS: Rajnagar
Dits: Moulovibazar',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:42:20',
                'updated_at' => '2019-06-23 18:00:01',
            ),
            18 => 
            array (
                'id' => 19,
                'student_id' => 22,
                'full_name' => 'Shohan Tusher',
                'relation' => NULL,
                'phone' => '01731984535',
                'email' => NULL,
                'address' => 'Fenchuganj
Rajonpur, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:42:57',
                'updated_at' => '2019-06-23 18:01:22',
            ),
            19 => 
            array (
                'id' => 20,
                'student_id' => 23,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:43:34',
                'updated_at' => '2019-06-23 18:04:22',
            ),
            20 => 
            array (
                'id' => 21,
                'student_id' => 24,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:44:44',
                'updated_at' => '2019-06-23 18:06:00',
            ),
            21 => 
            array (
                'id' => 22,
                'student_id' => 25,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:45:13',
                'updated_at' => '2019-06-23 18:06:54',
            ),
            22 => 
            array (
                'id' => 23,
                'student_id' => 26,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 09:45:28',
                'updated_at' => '2019-05-29 09:45:28',
            ),
            23 => 
            array (
                'id' => 24,
                'student_id' => 27,
                'full_name' => 'Jayed Jomin',
                'relation' => NULL,
                'phone' => '01728138737',
                'email' => NULL,
                'address' => 'Horipur 
Jointa, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 10:53:57',
                'updated_at' => '2019-06-27 12:03:57',
            ),
            24 => 
            array (
                'id' => 25,
                'student_id' => 28,
                'full_name' => 'Nasir Uddin',
                'relation' => NULL,
                'phone' => '01759739850',
                'email' => NULL,
                'address' => 'Mahmudabad R/A
Hobiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 11:36:36',
                'updated_at' => '2019-06-27 12:05:48',
            ),
            25 => 
            array (
                'id' => 26,
                'student_id' => 29,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 12:00:29',
                'updated_at' => '2019-06-27 12:13:01',
            ),
            26 => 
            array (
                'id' => 27,
                'student_id' => 30,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 12:48:47',
                'updated_at' => '2019-06-27 12:14:20',
            ),
            27 => 
            array (
                'id' => 28,
                'student_id' => 31,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 13:18:45',
                'updated_at' => '2019-06-27 12:16:14',
            ),
            28 => 
            array (
                'id' => 29,
                'student_id' => 32,
                'full_name' => 'Abul Khayer',
                'relation' => NULL,
                'phone' => '01719893661',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-29 14:03:56',
                'updated_at' => '2019-06-27 12:20:00',
            ),
            29 => 
            array (
                'id' => 30,
                'student_id' => 33,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 10:07:54',
                'updated_at' => '2019-06-27 12:23:05',
            ),
            30 => 
            array (
                'id' => 31,
                'student_id' => 34,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 10:28:45',
                'updated_at' => '2019-06-27 12:24:11',
            ),
            31 => 
            array (
                'id' => 32,
                'student_id' => 35,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 11:02:08',
                'updated_at' => '2019-06-27 13:04:34',
            ),
            32 => 
            array (
                'id' => 33,
                'student_id' => 36,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 11:47:42',
                'updated_at' => '2019-06-27 13:07:22',
            ),
            33 => 
            array (
                'id' => 34,
                'student_id' => 37,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 12:55:55',
                'updated_at' => '2019-06-27 13:15:28',
            ),
            34 => 
            array (
                'id' => 35,
                'student_id' => 38,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-30 13:19:31',
                'updated_at' => '2019-06-27 13:16:35',
            ),
            35 => 
            array (
                'id' => 36,
                'student_id' => 39,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 11:04:17',
                'updated_at' => '2019-06-27 13:20:08',
            ),
            36 => 
            array (
                'id' => 37,
                'student_id' => 40,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 11:55:32',
                'updated_at' => '2019-06-27 13:24:53',
            ),
            37 => 
            array (
                'id' => 38,
                'student_id' => 41,
                'full_name' => 'Dr. Nasim Ahmed',
                'relation' => NULL,
                'phone' => '01711858474',
                'email' => NULL,
                'address' => 'Noor jahan Hospital, Dorgah Gate. Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 12:25:06',
                'updated_at' => '2019-06-27 13:27:55',
            ),
            38 => 
            array (
                'id' => 39,
                'student_id' => 42,
                'full_name' => 'Md. Abdul Jalil',
                'relation' => NULL,
                'phone' => '01738110741',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 12:56:47',
                'updated_at' => '2019-06-27 13:29:12',
            ),
            39 => 
            array (
                'id' => 40,
                'student_id' => 43,
                'full_name' => 'Samar Halda',
                'relation' => NULL,
                'phone' => '01721202895',
                'email' => NULL,
                'address' => 'Pagla Bazar, Sunamganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-01 13:30:29',
                'updated_at' => '2019-06-27 13:30:37',
            ),
            40 => 
            array (
                'id' => 41,
                'student_id' => 44,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-03 09:54:58',
                'updated_at' => '2019-06-27 13:32:03',
            ),
            41 => 
            array (
                'id' => 42,
                'student_id' => 45,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 10:05:38',
                'updated_at' => '2019-06-29 09:44:34',
            ),
            42 => 
            array (
                'id' => 43,
                'student_id' => 46,
                'full_name' => 'Dipika Rani Ray',
                'relation' => 'Mother',
                'phone' => '01748944554',
                'email' => NULL,
                'address' => 'Notunpara
PO: Sachna Baza (3020)
Upozila: Jamalganj
Dist: Sunamganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 10:07:51',
                'updated_at' => '2019-06-29 09:46:06',
            ),
            43 => 
            array (
                'id' => 44,
                'student_id' => 47,
                'full_name' => 'Md. Faruk Miah',
                'relation' => NULL,
                'phone' => '01712920426',
                'email' => NULL,
                'address' => 'Rikabi Bazar Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 10:09:40',
                'updated_at' => '2019-06-29 09:47:16',
            ),
            44 => 
            array (
                'id' => 45,
                'student_id' => 48,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 10:11:25',
                'updated_at' => '2019-06-29 09:49:20',
            ),
            45 => 
            array (
                'id' => 46,
                'student_id' => 49,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 10:12:28',
                'updated_at' => '2019-06-29 09:50:05',
            ),
            46 => 
            array (
                'id' => 47,
                'student_id' => 50,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 10:13:38',
                'updated_at' => '2019-06-29 09:50:56',
            ),
            47 => 
            array (
                'id' => 48,
                'student_id' => 51,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 11:31:09',
                'updated_at' => '2019-06-29 09:52:22',
            ),
            48 => 
            array (
                'id' => 49,
                'student_id' => 52,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 12:37:16',
                'updated_at' => '2019-06-29 09:54:21',
            ),
            49 => 
            array (
                'id' => 50,
                'student_id' => 53,
                'full_name' => 'Setara Sultana Sweety',
                'relation' => 'Mother',
                'phone' => '01712254481',
                'email' => NULL,
                'address' => 'Vill: Burhanpur
Upozila: Nabiganj
Zila: Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-18 17:09:48',
                'updated_at' => '2019-06-29 09:55:28',
            ),
            50 => 
            array (
                'id' => 51,
                'student_id' => 54,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-19 12:27:01',
                'updated_at' => '2019-06-29 10:58:37',
            ),
            51 => 
            array (
                'id' => 52,
                'student_id' => 55,
                'full_name' => 'Md Jewel Chowdhury',
                'relation' => NULL,
                'phone' => '01716393310',
                'email' => NULL,
            'address' => '56- Tantipara (Ground Floor)
Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-19 13:08:27',
                'updated_at' => '2019-06-26 13:10:37',
            ),
            52 => 
            array (
                'id' => 53,
                'student_id' => 56,
                'full_name' => 'Md. Jalal Uddin',
                'relation' => NULL,
                'phone' => '01778126388',
                'email' => NULL,
                'address' => 'Charabhanga 
Itakhula 
Madhabpur, Habiganj',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-20 11:09:13',
                'updated_at' => '2019-06-26 13:09:26',
            ),
            53 => 
            array (
                'id' => 54,
                'student_id' => 57,
                'full_name' => 'Rubel Ahmed',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'Shahi Eidgah, sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 10:29:07',
                'updated_at' => '2019-06-26 13:00:58',
            ),
            54 => 
            array (
                'id' => 55,
                'student_id' => 58,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 10:52:24',
                'updated_at' => '2019-06-26 12:59:28',
            ),
            55 => 
            array (
                'id' => 56,
                'student_id' => 59,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-22 11:19:34',
                'updated_at' => '2019-06-26 12:58:37',
            ),
            56 => 
            array (
                'id' => 57,
                'student_id' => 60,
                'full_name' => 'Ashutosh Singha',
                'relation' => NULL,
                'phone' => '01711983509',
                'email' => NULL,
                'address' => 'Vatalia, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 10:47:07',
                'updated_at' => '2019-06-23 10:47:07',
            ),
            57 => 
            array (
                'id' => 58,
                'student_id' => 61,
                'full_name' => 'Mufti Moin Uddin',
                'relation' => NULL,
                'phone' => '01711950750',
                'email' => NULL,
                'address' => 'Dorgah Moholla, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 12:25:18',
                'updated_at' => '2019-06-23 12:25:18',
            ),
            58 => 
            array (
                'id' => 59,
                'student_id' => 62,
                'full_name' => 'Bedana Begum',
                'relation' => 'Mother',
                'phone' => '01720078538',
                'email' => NULL,
                'address' => 'Vill: Nolbacid
PO: Nolbacid
PS: Sherpur
Sherpur',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 16:17:15',
                'updated_at' => '2019-06-23 16:17:15',
            ),
            59 => 
            array (
                'id' => 60,
                'student_id' => 63,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-23 17:44:35',
                'updated_at' => '2019-06-26 12:58:05',
            ),
            60 => 
            array (
                'id' => 61,
                'student_id' => 64,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-24 10:49:24',
                'updated_at' => '2019-06-26 12:22:16',
            ),
            61 => 
            array (
                'id' => 62,
                'student_id' => 65,
                'full_name' => 'Mujibur Rahman',
                'relation' => NULL,
                'phone' => '01712172986',
                'email' => NULL,
                'address' => 'Vill: Raygor 
PO: Dhakadakshin
PS: Golapganj
Dist: Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-25 12:30:33',
                'updated_at' => '2019-06-25 12:30:33',
            ),
            62 => 
            array (
                'id' => 63,
                'student_id' => 66,
                'full_name' => 'Md. Saiful Islam',
                'relation' => NULL,
                'phone' => '01718389089',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:06:57',
                'updated_at' => '2019-06-29 11:06:57',
            ),
            63 => 
            array (
                'id' => 64,
                'student_id' => 67,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:08:18',
                'updated_at' => '2019-06-29 11:08:18',
            ),
            64 => 
            array (
                'id' => 65,
                'student_id' => 68,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:09:33',
                'updated_at' => '2019-06-29 11:09:33',
            ),
            65 => 
            array (
                'id' => 66,
                'student_id' => 69,
                'full_name' => 'Lipi Bhattacharjee',
                'relation' => 'N/A',
                'phone' => '01712109624',
                'email' => NULL,
            'address' => 'Shopnil 29/1, Ramerdighirpar (West Side)
Mirjajangal, Sylhet- 3100',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:10:15',
                'updated_at' => '2019-06-29 11:10:15',
            ),
            66 => 
            array (
                'id' => 67,
                'student_id' => 70,
                'full_name' => 'Akter Hosen',
                'relation' => 'Brother',
                'phone' => '01741974369',
                'email' => NULL,
                'address' => 'Maa-Manzil
Block- A 
Nibas- 14
Modina Market, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:11:50',
                'updated_at' => '2019-06-29 11:11:50',
            ),
            67 => 
            array (
                'id' => 68,
                'student_id' => 71,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:12:19',
                'updated_at' => '2019-06-29 11:12:19',
            ),
            68 => 
            array (
                'id' => 69,
                'student_id' => 72,
                'full_name' => 'Dr. Sheikh Mohammad Misbah Uddin',
                'relation' => NULL,
                'phone' => '01733775300',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:12:58',
                'updated_at' => '2019-06-29 11:12:58',
            ),
            69 => 
            array (
                'id' => 70,
                'student_id' => 73,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:13:51',
                'updated_at' => '2019-06-29 11:13:51',
            ),
            70 => 
            array (
                'id' => 71,
                'student_id' => 74,
                'full_name' => 'Biplob Roy',
                'relation' => NULL,
                'phone' => '01730906030',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-29 11:14:26',
                'updated_at' => '2019-06-29 11:14:26',
            ),
            71 => 
            array (
                'id' => 72,
                'student_id' => 75,
                'full_name' => 'Punit Yadab',
                'relation' => NULL,
                'phone' => '01716611060',
                'email' => NULL,
                'address' => 'Northeast Boy Hostel, Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-30 12:21:26',
                'updated_at' => '2019-06-30 12:21:26',
            ),
            72 => 
            array (
                'id' => 73,
                'student_id' => 76,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-06-30 13:23:43',
                'updated_at' => '2019-06-30 13:23:43',
            ),
            73 => 
            array (
                'id' => 74,
                'student_id' => 77,
                'full_name' => 'Rajnesh Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NMEC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-18 11:15:09',
                'updated_at' => '2019-07-20 11:25:02',
            ),
            74 => 
            array (
                'id' => 75,
                'student_id' => 78,
                'full_name' => 'Rainesh Yadav',
                'relation' => NULL,
                'phone' => '01727285916',
                'email' => NULL,
                'address' => 'NMEC Boy Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-18 13:19:02',
                'updated_at' => '2019-07-18 13:19:02',
            ),
            75 => 
            array (
                'id' => 76,
                'student_id' => 79,
                'full_name' => 'Neraj Ali Shah',
                'relation' => NULL,
                'phone' => 'NEMC Boys Hostel',
                'email' => NULL,
                'address' => '01630870858',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 11:17:40',
                'updated_at' => '2019-07-20 11:17:40',
            ),
            76 => 
            array (
                'id' => 77,
                'student_id' => 80,
                'full_name' => 'Rainish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 11:54:24',
                'updated_at' => '2019-07-20 11:54:24',
            ),
            77 => 
            array (
                'id' => 78,
                'student_id' => 81,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'Sylhet',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 12:38:51',
                'updated_at' => '2019-07-20 12:38:51',
            ),
            78 => 
            array (
                'id' => 79,
                'student_id' => 82,
                'full_name' => 'Rajneesh Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-20 13:05:57',
                'updated_at' => '2019-07-20 13:05:57',
            ),
            79 => 
            array (
                'id' => 80,
                'student_id' => 83,
                'full_name' => 'Rajnesh Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-22 11:54:08',
                'updated_at' => '2019-07-22 11:54:08',
            ),
            80 => 
            array (
                'id' => 81,
                'student_id' => 84,
                'full_name' => 'Rajnish',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-22 12:30:44',
                'updated_at' => '2019-07-22 12:30:44',
            ),
            81 => 
            array (
                'id' => 82,
                'student_id' => 85,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-22 13:09:18',
                'updated_at' => '2019-07-22 13:09:18',
            ),
            82 => 
            array (
                'id' => 83,
                'student_id' => 86,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boy Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 09:52:32',
                'updated_at' => '2019-07-24 09:52:32',
            ),
            83 => 
            array (
                'id' => 84,
                'student_id' => 87,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 10:25:53',
                'updated_at' => '2019-07-24 10:25:53',
            ),
            84 => 
            array (
                'id' => 85,
                'student_id' => 88,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 11:06:52',
                'updated_at' => '2019-07-24 11:06:52',
            ),
            85 => 
            array (
                'id' => 86,
                'student_id' => 89,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 11:29:17',
                'updated_at' => '2019-07-24 11:29:17',
            ),
            86 => 
            array (
                'id' => 87,
                'student_id' => 90,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 12:05:38',
                'updated_at' => '2019-07-24 12:05:38',
            ),
            87 => 
            array (
                'id' => 88,
                'student_id' => 91,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 12:53:36',
                'updated_at' => '2019-07-24 12:53:36',
            ),
            88 => 
            array (
                'id' => 89,
                'student_id' => 92,
                'full_name' => 'Rajnish',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-24 13:14:51',
                'updated_at' => '2019-07-24 13:14:51',
            ),
            89 => 
            array (
                'id' => 90,
                'student_id' => 93,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 10:26:15',
                'updated_at' => '2019-07-25 10:26:15',
            ),
            90 => 
            array (
                'id' => 91,
                'student_id' => 94,
                'full_name' => 'Birendra Kumar Shah',
                'relation' => NULL,
                'phone' => '01733988420',
                'email' => NULL,
                'address' => 'Siraha, Nepal',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 11:04:50',
                'updated_at' => '2019-07-25 11:04:50',
            ),
            91 => 
            array (
                'id' => 92,
                'student_id' => 95,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-25 11:27:19',
                'updated_at' => '2019-07-25 11:27:19',
            ),
            92 => 
            array (
                'id' => 93,
                'student_id' => 96,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-27 11:40:07',
                'updated_at' => '2019-07-31 12:22:41',
            ),
            93 => 
            array (
                'id' => 94,
                'student_id' => 97,
                'full_name' => 'Bindo Pantha',
                'relation' => NULL,
                'phone' => '01918217600',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-31 12:13:18',
                'updated_at' => '2019-07-31 12:22:29',
            ),
            94 => 
            array (
                'id' => 95,
                'student_id' => 98,
                'full_name' => 'Reshan shah',
                'relation' => NULL,
                'phone' => '01630985038',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-07-31 12:13:42',
                'updated_at' => '2019-07-31 12:22:11',
            ),
            95 => 
            array (
                'id' => 96,
                'student_id' => 99,
                'full_name' => 'Adarsh Yadav',
                'relation' => NULL,
                'phone' => '01778569090',
                'email' => NULL,
                'address' => 'NEMC Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 11:05:00',
                'updated_at' => '2019-08-05 11:05:00',
            ),
            96 => 
            array (
                'id' => 97,
                'student_id' => 100,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 11:30:29',
                'updated_at' => '2019-08-05 11:30:29',
            ),
            97 => 
            array (
                'id' => 98,
                'student_id' => 101,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 11:40:44',
                'updated_at' => '2019-08-05 11:40:44',
            ),
            98 => 
            array (
                'id' => 99,
                'student_id' => 102,
                'full_name' => 'Anushka Thapa',
                'relation' => NULL,
                'phone' => '01192254550',
                'email' => NULL,
                'address' => 'NEMC Girls Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-05 12:01:31',
                'updated_at' => '2019-08-05 12:01:31',
            ),
            99 => 
            array (
                'id' => 100,
                'student_id' => 103,
                'full_name' => 'Ocean Magar',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 10:08:40',
                'updated_at' => '2019-08-07 10:08:40',
            ),
            100 => 
            array (
                'id' => 101,
                'student_id' => 104,
                'full_name' => 'Punit Yadav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => 'NEMC',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 10:36:35',
                'updated_at' => '2019-08-07 10:36:35',
            ),
            101 => 
            array (
                'id' => 102,
                'student_id' => 105,
                'full_name' => 'Aman Yadav',
                'relation' => NULL,
                'phone' => '01792382241',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 12:52:19',
                'updated_at' => '2019-08-07 12:52:19',
            ),
            102 => 
            array (
                'id' => 103,
                'student_id' => 106,
                'full_name' => 'Shree Kumar Shrestha',
                'relation' => NULL,
                'phone' => '016219980954',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 13:15:56',
                'updated_at' => '2019-08-07 13:15:56',
            ),
            103 => 
            array (
                'id' => 104,
                'student_id' => 107,
                'full_name' => 'Rupnarayan Mandal',
                'relation' => NULL,
                'phone' => '01781878946',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-07 13:34:24',
                'updated_at' => '2019-08-07 13:34:24',
            ),
            104 => 
            array (
                'id' => 105,
                'student_id' => 108,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 10:11:00',
                'updated_at' => '2019-08-08 10:11:00',
            ),
            105 => 
            array (
                'id' => 106,
                'student_id' => 109,
                'full_name' => 'Ravi Rauniyar',
                'relation' => NULL,
                'phone' => '0170598587',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 10:46:50',
                'updated_at' => '2019-08-08 10:46:50',
            ),
            106 => 
            array (
                'id' => 107,
                'student_id' => 110,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 11:14:55',
                'updated_at' => '2019-08-08 11:14:55',
            ),
            107 => 
            array (
                'id' => 108,
                'student_id' => 111,
                'full_name' => 'Aman Yadav',
                'relation' => NULL,
                'phone' => '01792382241',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 11:39:56',
                'updated_at' => '2019-08-08 11:39:56',
            ),
            108 => 
            array (
                'id' => 109,
                'student_id' => 112,
                'full_name' => 'Gaurav Subedi',
                'relation' => NULL,
                'phone' => '01732075040',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 11:58:21',
                'updated_at' => '2019-08-08 11:58:21',
            ),
            109 => 
            array (
                'id' => 110,
                'student_id' => 113,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 12:21:06',
                'updated_at' => '2019-08-08 12:21:06',
            ),
            110 => 
            array (
                'id' => 111,
                'student_id' => 114,
                'full_name' => 'Rajnish Yadav',
                'relation' => NULL,
                'phone' => '01727285996',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-08 12:31:39',
                'updated_at' => '2019-08-08 12:31:39',
            ),
            111 => 
            array (
                'id' => 114,
                'student_id' => 117,
                'full_name' => 'Rajib Yadav',
                'relation' => NULL,
                'phone' => '01855717591',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:05:56',
                'updated_at' => '2019-08-20 13:05:56',
            ),
            112 => 
            array (
                'id' => 115,
                'student_id' => 118,
                'full_name' => 'Rupnarayan Mandal',
                'relation' => NULL,
                'phone' => '01781878946',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:06:59',
                'updated_at' => '2019-08-20 13:06:59',
            ),
            113 => 
            array (
                'id' => 116,
                'student_id' => 119,
                'full_name' => 'Suresh Kumar Yadav',
                'relation' => NULL,
                'phone' => '01792255236',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:07:57',
                'updated_at' => '2019-08-20 13:07:57',
            ),
            114 => 
            array (
                'id' => 117,
                'student_id' => 120,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:08:45',
                'updated_at' => '2019-08-20 13:08:45',
            ),
            115 => 
            array (
                'id' => 118,
                'student_id' => 121,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:09:17',
                'updated_at' => '2019-08-20 13:09:17',
            ),
            116 => 
            array (
                'id' => 119,
                'student_id' => 122,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:09:53',
                'updated_at' => '2019-08-20 13:09:53',
            ),
            117 => 
            array (
                'id' => 120,
                'student_id' => 123,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:10:23',
                'updated_at' => '2019-08-20 13:10:23',
            ),
            118 => 
            array (
                'id' => 121,
                'student_id' => 124,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:11:32',
                'updated_at' => '2019-08-20 13:11:32',
            ),
            119 => 
            array (
                'id' => 122,
                'student_id' => 125,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-20 13:12:11',
                'updated_at' => '2019-08-20 13:12:11',
            ),
            120 => 
            array (
                'id' => 123,
                'student_id' => 126,
                'full_name' => 'Dr. Niroj Karki',
                'relation' => NULL,
                'phone' => '01721370114',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 10:50:05',
                'updated_at' => '2019-08-21 10:50:05',
            ),
            121 => 
            array (
                'id' => 124,
                'student_id' => 127,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 10:50:46',
                'updated_at' => '2019-08-21 10:50:46',
            ),
            122 => 
            array (
                'id' => 126,
                'student_id' => 129,
                'full_name' => 'Subash Chandra Yadav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:00:05',
                'updated_at' => '2019-08-21 13:00:05',
            ),
            123 => 
            array (
                'id' => 127,
                'student_id' => 130,
                'full_name' => 'Sameer Shrivastav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:00:32',
                'updated_at' => '2019-08-21 13:00:32',
            ),
            124 => 
            array (
                'id' => 128,
                'student_id' => 131,
                'full_name' => 'Sameer Srivastav',
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:01:21',
                'updated_at' => '2019-08-21 13:01:21',
            ),
            125 => 
            array (
                'id' => 129,
                'student_id' => 132,
                'full_name' => 'Punit Yadav',
                'relation' => NULL,
                'phone' => '01766177800',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:02:02',
                'updated_at' => '2019-08-21 13:02:02',
            ),
            126 => 
            array (
                'id' => 130,
                'student_id' => 133,
                'full_name' => 'Dr. Saddam Ansari',
                'relation' => NULL,
                'phone' => '01792254031',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:02:26',
                'updated_at' => '2019-08-21 13:02:26',
            ),
            127 => 
            array (
                'id' => 131,
                'student_id' => 134,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:03:11',
                'updated_at' => '2019-08-21 13:03:11',
            ),
            128 => 
            array (
                'id' => 132,
                'student_id' => 135,
                'full_name' => 'MD. Saddam Ansari',
                'relation' => NULL,
                'phone' => '01792254031',
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:03:50',
                'updated_at' => '2019-08-21 13:03:50',
            ),
            129 => 
            array (
                'id' => 133,
                'student_id' => 136,
                'full_name' => 'Bhupendra das',
                'relation' => NULL,
                'phone' => '01998848729',
                'email' => NULL,
                'address' => 'NEMC Boys Hostel',
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:04:40',
                'updated_at' => '2019-08-21 13:04:40',
            ),
            130 => 
            array (
                'id' => 134,
                'student_id' => 137,
                'full_name' => NULL,
                'relation' => NULL,
                'phone' => NULL,
                'email' => NULL,
                'address' => NULL,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-08-21 13:04:59',
                'updated_at' => '2019-08-21 13:04:59',
            ),
        ));
        
        
    }
}