<?php

use Illuminate\Database\Seeder;

class PaymentDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('payment_details')->delete();
        
        \DB::table('payment_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'payment_type_id' => 1,
                'student_category_id' => 1,
                'course_id' => 1,
                'amount' => '1800000.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'payment_type_id' => 1,
                'student_category_id' => 2,
                'course_id' => 1,
                'amount' => '40500.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'payment_type_id' => 1,
                'student_category_id' => 3,
                'course_id' => 1,
                'amount' => '192000.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'payment_type_id' => 1,
                'student_category_id' => 4,
                'course_id' => 1,
                'amount' => '192000.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'payment_type_id' => 1,
                'student_category_id' => 5,
                'course_id' => 1,
                'amount' => '192000.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'payment_type_id' => 1,
                'student_category_id' => 1,
                'course_id' => 2,
                'amount' => '1000000.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'payment_type_id' => 1,
                'student_category_id' => 3,
                'course_id' => 2,
                'amount' => '192000.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'payment_type_id' => 1,
                'student_category_id' => 4,
                'course_id' => 2,
                'amount' => '192000.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'payment_type_id' => 1,
                'student_category_id' => 5,
                'course_id' => 2,
                'amount' => '192000.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'payment_type_id' => 3,
                'student_category_id' => 1,
                'course_id' => 1,
                'amount' => '8000.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'payment_type_id' => 3,
                'student_category_id' => 1,
                'course_id' => 2,
                'amount' => '6000.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'payment_type_id' => 4,
                'student_category_id' => 1,
                'course_id' => 1,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'payment_type_id' => 4,
                'student_category_id' => 2,
                'course_id' => 1,
                'amount' => '2.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'payment_type_id' => 4,
                'student_category_id' => 3,
                'course_id' => 1,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'payment_type_id' => 4,
                'student_category_id' => 4,
                'course_id' => 1,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'payment_type_id' => 4,
                'student_category_id' => 5,
                'course_id' => 1,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'payment_type_id' => 4,
                'student_category_id' => 1,
                'course_id' => 2,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'payment_type_id' => 4,
                'student_category_id' => 3,
                'course_id' => 2,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'payment_type_id' => 4,
                'student_category_id' => 4,
                'course_id' => 2,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'payment_type_id' => 4,
                'student_category_id' => 5,
                'course_id' => 2,
                'amount' => '20.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'payment_type_id' => 5,
                'student_category_id' => 1,
                'course_id' => 1,
                'amount' => '100.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'payment_type_id' => 5,
                'student_category_id' => 2,
                'course_id' => 1,
                'amount' => '10.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'payment_type_id' => 5,
                'student_category_id' => 1,
                'course_id' => 2,
                'amount' => '100.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'payment_type_id' => 6,
                'student_category_id' => 1,
                'course_id' => 1,
                'amount' => '5000.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'payment_type_id' => 6,
                'student_category_id' => 2,
                'course_id' => 1,
                'amount' => '300.00',
                'currency_code' => 'USD',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'payment_type_id' => 6,
                'student_category_id' => 1,
                'course_id' => 2,
                'amount' => '5000.00',
                'currency_code' => 'TK',
                'status' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2019-05-14 15:46:34',
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}