<?php

use Illuminate\Database\Seeder;

class SessionDetailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('session_details')->delete();
        
        \DB::table('session_details')->insert(array (
            0 => 
            array (
                'id' => 1,
                'session_id' => 1,
                'course_id' => 1,
                'batch_number' => '1',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-14 15:53:44',
                'updated_at' => '2019-05-15 09:48:49',
                'deleted_at' => '2019-05-15 09:48:49',
            ),
            1 => 
            array (
                'id' => 2,
                'session_id' => 1,
                'course_id' => 2,
                'batch_number' => '1',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-14 15:53:44',
                'updated_at' => '2019-05-15 09:48:49',
                'deleted_at' => '2019-05-15 09:48:49',
            ),
            2 => 
            array (
                'id' => 3,
                'session_id' => 1,
                'course_id' => 1,
                'batch_number' => '18',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 09:48:49',
                'updated_at' => '2019-05-15 09:55:59',
                'deleted_at' => '2019-05-15 09:55:59',
            ),
            3 => 
            array (
                'id' => 4,
                'session_id' => 1,
                'course_id' => 2,
                'batch_number' => '1',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 09:48:49',
                'updated_at' => '2019-05-15 09:55:59',
                'deleted_at' => '2019-05-15 09:55:59',
            ),
            4 => 
            array (
                'id' => 5,
                'session_id' => 1,
                'course_id' => 1,
                'batch_number' => '18',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 09:55:59',
                'updated_at' => '2019-05-15 10:07:17',
                'deleted_at' => '2019-05-15 10:07:17',
            ),
            5 => 
            array (
                'id' => 6,
                'session_id' => 1,
                'course_id' => 2,
                'batch_number' => '1',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 09:55:59',
                'updated_at' => '2019-05-15 10:07:17',
                'deleted_at' => '2019-05-15 10:07:17',
            ),
            6 => 
            array (
                'id' => 7,
                'session_id' => 1,
                'course_id' => 1,
                'batch_number' => '22',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 10:07:17',
                'updated_at' => '2019-05-15 12:49:23',
                'deleted_at' => '2019-05-15 12:49:23',
            ),
            7 => 
            array (
                'id' => 8,
                'session_id' => 1,
                'course_id' => 2,
                'batch_number' => '5',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 10:07:17',
                'updated_at' => '2019-05-15 12:49:23',
                'deleted_at' => '2019-05-15 12:49:23',
            ),
            8 => 
            array (
                'id' => 9,
                'session_id' => 1,
                'course_id' => 1,
                'batch_number' => '22',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 12:49:23',
                'updated_at' => '2019-05-15 12:51:36',
                'deleted_at' => '2019-05-15 12:51:36',
            ),
            9 => 
            array (
                'id' => 10,
                'session_id' => 1,
                'course_id' => 2,
                'batch_number' => '5',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 12:49:23',
                'updated_at' => '2019-05-15 12:51:36',
                'deleted_at' => '2019-05-15 12:51:36',
            ),
            10 => 
            array (
                'id' => 11,
                'session_id' => 1,
                'course_id' => 1,
                'batch_number' => '22',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 12:51:36',
                'updated_at' => '2019-05-15 12:51:36',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'session_id' => 1,
                'course_id' => 2,
                'batch_number' => '5',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-05-15 12:51:36',
                'updated_at' => '2019-05-15 12:51:36',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'session_id' => 2,
                'course_id' => 1,
                'batch_number' => '22',
                'development_fee_local' => '1800000.00',
                'development_fee_foreign' => '40500.00',
                'tuition_fee_local' => '8000.00',
                'tuition_fee_foreign' => '100.00',
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-10-05 10:34:28',
                'updated_at' => '2019-10-05 10:34:28',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'session_id' => 2,
                'course_id' => 2,
                'batch_number' => '5',
                'development_fee_local' => '1000000.00',
                'development_fee_foreign' => NULL,
                'tuition_fee_local' => '6000.00',
                'tuition_fee_foreign' => NULL,
                'total_phases' => 4,
                'status' => 0,
                'created_by' => 1,
                'updated_by' => 0,
                'created_at' => '2019-10-05 10:34:28',
                'updated_at' => '2019-10-05 10:34:28',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}